# Generated by Django 6.0.6 on 2026-07-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_category_name_unique_producttype_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
