# Generated by Django 6.0.6 on 2026-07-14 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerializedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('serial', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='producttype',
            name='model_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
