# Generated by Django 6.0.6 on 2026-07-14 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_serializeditem_alter_producttype_model_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serializeditem',
            options={'ordering': ['serial_number']},
        ),
        migrations.RemoveField(
            model_name='serializeditem',
            name='code',
        ),
        migrations.RemoveField(
            model_name='serializeditem',
            name='name',
        ),
        migrations.AddField(
            model_name='serializeditem',
            name='last_work_order_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serializeditem',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='serialized_items', to='inventory.producttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serializeditem',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='serializeditem',
            name='serial_number',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serializeditem',
            name='status',
            field=models.CharField(choices=[('available', 'Available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='serializeditem',
            name='serial',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
