# Generated by Django 6.0.6 on 2026-07-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_serializeditem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serializeditem",
            name="qr_code",
        ),
    ]
