# Generated by Django 6.0.6 on 2026-07-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_serializeditem_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
