# Generated by Django 6.0.6 on 2026-07-14 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_purchaseorder_purchaseorderlineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="serializeditem",
            name="purchase_order_line_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="serialized_items",
                to="inventory.purchaseorderlineitem",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partially_received", "Partially received"),
                    ("received", "Received"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
