# Generated by Django 6.0.6 on 2026-07-16 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_workorder_workorderlineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="serializeditem",
            name="work_order_line_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="serialized_items",
                to="inventory.workorderlineitem",
            ),
        ),
        migrations.AlterField(
            model_name="serializeditem",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("out", "Out"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In progress"),
                    ("fulfilled", "Fulfilled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
