# Generated by Django 6.0.6 on 2026-07-17 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_serializeditem_work_order_line_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="parent_work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplementaries",
                to="inventory.workorder",
            ),
        ),
    ]
