# Generated by Django 6.0.6 on 2026-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_workorder_parent_work_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serializeditem",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("out", "Out"),
                    ("damaged", "Damaged"),
                    ("missing", "Missing"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
