# Generated by Django 6.0.6 on 2026-07-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_serializeditem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In progress"),
                    ("fulfilled", "Fulfilled"),
                    ("returned", "Returned"),
                    ("partially_returned", "Partially returned"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
