# Generated by Django 6.0.6 on 2026-07-24 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_serializeditem_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="supplementary_sequence",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.UniqueConstraint(
                fields=("parent_work_order", "supplementary_sequence"),
                name="unique_supplementary_sequence_per_parent",
            ),
        ),
    ]
