# Generated by Django 6.0.6 on 2026-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_box_serializeditem_box"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In progress"),
                    ("fulfilled", "Fulfilled"),
                    ("returned", "Returned"),
                    ("partially_returned", "Partially returned"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
