# Generated by Django 6.0.6 on 2026-08-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_damagereport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serializeditem",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("out", "Out"),
                    ("damaged", "Damaged"),
                    ("missing", "Missing"),
                    ("in_maintenance", "In maintenance"),
                    ("written_off", "Written off"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
