# Generated by Django 6.0.6 on 2026-08-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_maintenanceorder_serializeditem_maintenance_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
