# Generated by Django 6.0.6 on 2026-08-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_maintenanceordernote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
